build_dir ?= build
source = loader.c
object = $(addprefix $(build_dir)/, $(patsubst %.c, %.o, $(source)))
skeleton_dir = ./build/skel/
# $(info $(object))

CC = clang

# If libbpf is installed system wide
# LIBBPF_HEADER=$(shell pkg-config --cflags libbpf)
# LIBBPF_LIBS=$(shell pkg-config --libs libbpf)

LIBBPF_HEADER=-I ../../../deps/usr/include
LIBBPF_LIBS=-L ../../../deps/usr/lib64 -lbpf -lelf -lz

CFLAGS = -O3 -g -Wall
CFLAGS += -I $(skeleton_dir)
CFLAGS += -I ../../../libs
CFLAGS += $(LIBBPF_HEADER)
LDFLAGS = $(LIBBPF_LIBS)

# Skeleton header files that loader relies on
bpf_names = exp
skeletons = $(addprefix $(skeleton_dir), $(addsuffix .skel.h, $(bpf_names)))
$(info $(skeletons))

default: $(object)

$(build_dir)/%.o: %.c $(skeletons)
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

