"""
Generate a pcap file to be used by the workload generator
(DPDK Burst Replay)

First use Mutilate to load some key-value pairs into the Memcached (use
loadonly flag). Then use the PCAP file generated with this script to generate
load.

The scripts uses a zipfian distribution in the order of requested entries.
The default zipfian parameter is zero which makes results in a uniform
distribution. Increasing it will create a more skewed workload.

@author: Farbod Shahinfar
@date: January, 2025
"""
import os
import sys
from socket import htons
import ctypes
from scapy.all import Ether, IP, UDP, Raw, wrpcap
from argparse import ArgumentParser
from multiprocessing import Pool
curdir = os.path.abspath(os.path.dirname(sys.argv[0]))
common_lib_dir = os.path.join(curdir, '../../libs/common/')
sys.path.insert(0, common_lib_dir)
from zipf import Zipf

src_mac = '9c:dc:71:5d:61:01'
dst_mac = '9c:dc:71:5b:42:81'
src_ip = '192.168.1.2'
dst_ip = '192.168.1.1'
src_port = 5432
dst_port = 8080
payload = 'get {0}\r\n\0'

class UDPMeta(ctypes.Structure):
    """
    typedef struct __attribute__ ((__packed__)) {
  uint16_t req_id;
  uint16_t seq_no;
  uint16_t datagrams;
  uint16_t reserved;
} udp_header_t;
    """
    _fields_ = [
            ('req_id', ctypes.c_int16),
            ('seq_no', ctypes.c_int16),
            ('dtagrams', ctypes.c_int16),
            ('reserved', ctypes.c_int16),
            ]


def parse_args():
    parser = ArgumentParser()
    parser.add_argument('--records', '-r', default=128, type=int, help='number of records in the Memcached data base')
    parser.add_argument('--output', '-o', default='test.pcap', type=str, help='output file path')
    parser.add_argument('--zipf', '-z', default=0, type=float, help='zipf alpha')
    parser.add_argument('key_len', type=int, help='the length of keys generated by Mutilate')
    args = parser.parse_args()
    return args


def form_packet(saddr: str, source: int, daddr: str, dest: int, payload: str):
    eth_header = Ether(src=src_mac, dst=dst_mac)
    ip_header = IP(src=saddr, dst=daddr, ttl=64)
    udp_header = UDP(dport=dest, sport=source)
    packet = eth_header / ip_header / udp_header / Raw(load=payload)
    packet[IP].chksum = None
    packet[UDP].chksum = None
    return packet


def format_key(key_index: int, key_len: int):
    tmp = str(key_index)
    leading_zeros = key_len - len(tmp)
    return ('0' * leading_zeros) + tmp


def fn(arg):
    req_id, key_index, key_len = arg
    key = format_key(key_index, key_len)
    req = payload.format(key)
    meta = bytes(UDPMeta(htons(req_id), 0, htons(1), 0))
    assert(len(meta) == 8)
    body = meta + req.encode('ascii')
    return form_packet(src_ip, src_port, dst_ip, dst_port, body)


def main(args):
    # The number of packets in the PCAP file is 4 times more than the number of
    # records in the database. This should be enough to create a good
    # distribution of packets
    r = args.records * 4
    z = Zipf(args.records, args.zipf)
    pkt_info = []
    for i in range(r):
        key_index = z.sample()
        req_id = i % (1 << 15)
        pkt_info.append((req_id, key_index, args.key_len))
    print('Generating packets...')
    with Pool(10) as p:
        pkts = p.map(fn, pkt_info)
    print('Writing packets to disk...')
    wrpcap(args.output, pkts)
    print('Generated a pcap file with', r, 'packets. Zipf=', args.zipf,
            'working set=', args.records)


if __name__ == "__main__":
    args = parse_args()
    print('Notice: the source/dest MAC address is hardcoded')
    print('src mac:', src_mac)
    print('dst mac:', dst_mac)
    print('Notice: the source/dest IP address is hardcoded')
    print('src ip:', src_ip)
    print('dst ip:', dst_ip)
    main(args)
