#!/usr/bin/env bash
# config.sh – auto-generated by scripts/user_setup_machines.sh
# Do not edit by hand; re-run the setup script to regenerate.

DUT_SERVER=""         # control-interface hostname/IP of DUT
DUT_USER=""           # SSH username for DUT
GEN_EXP_IP=""      # experiment IP of the generator (192.168.1.2)
DUT_NET_IFACE="" # experiment NIC name on DUT
DUT_MAC_ADDR=""   # MAC of DUT's experiment NIC

# Extra fields (available for convenience in experiment scripts)
GEN_SERVER=""         # control-interface hostname/IP of generator
GEN_USER=""           # SSH username for generator
GEN_NET_IFACE="" # experiment NIC name on generator
GEN_MAC_ADDR=""   # MAC of generator's experiment NIC
DUT_EXP_IP=""      # experiment IP of DUT (192.168.1.1)

_check_config() {
    # The script including this can define an array with `_must_define` and
    # then use this function to enforce it
    for field in ${_must_define[@]}; do
        if [ -z "${!field}" ]; then
            echo "Error:"
            echo "\"$field\" was not defined"
            echo "This script requires all these variables: ${_must_define[@]}"
            exit 1
        fi
    done
}
