---
traces:
  - path: "lpm_zipf_0.pcap"
    tx_queues: 4
numacore: 0 # This may be set to 1 in some machines. 
max_mpps: -1
max_mbps: -1
nbruns: 100000000
timeout: 60
write_csv: True
wait_enter: False
slow_mode: False
stats:
  - pci_id: <Fill this with $NET_PCI>
    file_name: "result_v1_core1.csv"
send_port_pci: <Fill this with $NET_PCI>
loglevel: INFO