build_dir ?= build
source = loader.c
object = $(addprefix $(build_dir)/, $(patsubst %.c, %.o, $(source)))
skeleton_dir = ./build/skel/
# $(info $(object))

CC = clang
CFLAGS = -O3 -g -Wall $(shell pkg-config --cflags libbpf)
CFLAGS += -I $(skeleton_dir)
LDFLAGS = $(shell pkg-config --libs libbpf)

# Skeleton header files that loader relies on
bpf_names = macchiato cappuccino lungo
skeletons = $(addprefix $(skeleton_dir), $(addsuffix .skel.h, $(bpf_names)))
$(info $(skeletons))

default: $(object)

$(build_dir)/%.o: %.c $(skeletons)
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)
