LLC ?= llc-19
CLANG ?= clang-19

LIBBPF_HEADER=../../deps/usr/include

build_dir ?= build
skel_dir = $(build_dir)/skel

# define headers as dependencies so the program is recompiled after changes
bpf_headers=$(shell find ./include/ -name '*.h')


# out_obj = $(skel_dir)/dat_enhanced.skel.h
# out_obj += $(skel_dir)/dat_cost_of_dummy_stage.skel.h
# out_obj += $(skel_dir)/drop.skel.h
out_obj = $(addprefix $(skel_dir)/, $(addsuffix .skel.h, $(basename $(wildcard *.bax))))

REPO_LIB_DIR = ../../libs/

# debuging variables ...
$(info $(out_obj))
# $(info $(bpf_headers))

BPF_CFLAGS ?=
BPF_CFLAGS += -target bpf 
BPF_CFLAGS += -O2 -g
BPF_CFLAGS += -std=gnu17
BPF_CFLAGS += -Werror
BPF_CFLAGS += -Wno-unused-value
BPF_CFLAGS += -Wno-pointer-sign
BPF_CFLAGS += -Wno-compare-distinct-pointer-types
BPF_CFLAGS += -Wno-address-of-packed-member
BPF_CFLAGS += -Wno-incompatible-pointer-types
BPF_CFLAGS += -D __KERNEL__ -D __BPF__ -D __bpf__
BPF_CFLAGS += -D __BPF_FEATURE_ADDR_SPACE_CAST
BPF_CFLAGS += -I ./include/ -I ./
BPF_CFLAGS += -I $(REPO_LIB_DIR)
BPF_CFLAGS += -I $(LIBBPF_HEADER)

EXTRA_CFLAGS ?=

# Rules
.PHONY: all

all: $(skel_dir) $(out_obj)

$(skel_dir):
	mkdir -p $@

$(build_dir)/%.bpf.c: %.bax
	/bin/bash ../../libs/bax/cbax.sh $< $@

$(build_dir)/%.bpf.ll: $(build_dir)/%.bpf.c
	$(CLANG) $(EXTRA_CFLAGS) $(BPF_CFLAGS) -emit-llvm -c $< -o $@.tmp
	mv $@.tmp $@

$(build_dir)/%.bpf.o: $(build_dir)/%.bpf.ll  $(bpf_headers)
	$(LLC) -mcpu=probe -march=bpf -filetype=obj -o $@ $<
	cp $@ $@.keep

$(skel_dir)/%.skel.h: $(build_dir)/%.bpf.o
	name=$$(echo $@ | cut -d / -f 3 | cut -d '.' -f 1); \
		 bpftool gen skeleton $< name $$name > $@.tmp
	mv $@.tmp $@
